CREATE TABLE IF NOT EXISTS Offer (
    OFFER_ID BIGINT PRIMARY KEY,
    BRAND_ID INTEGER,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INTEGER,
    SIZE VARCHAR(2),
    MODEL VARCHAR(4),
    QUALITY VARCHAR(3),
    PRIORITY INTEGER,
    PRICE DECIMAL,
    CURR VARCHAR(255)
);
